/**
 * pandora-box-manifest — builder component manifests (field descriptors) for the Pandora Box
 * low-code engine's layout components. Generated by the engine extractor (the SSOT) and shipped
 * as DATA, so a builder OR a project reads the exact field config the builder uses
 * ("builder == delivered"). Pairs 1:1 with `pandora-box-layout` (the runtime components).
 *
 * Zero runtime deps: the manifest is plain JSON + these structural types (a copy of the engine
 * protocol). Use the exported types directly, or assign to your own `ComponentManifest`
 * (e.g. from pandora-box-react) with a cast — the shapes match.
 */
import manifestData from './manifest.json';

export interface FieldOption {
    label: string;
    value: string | number | boolean;
}

export type FieldDescriptor =
    | { kind: 'text' }
    | { kind: 'textarea' }
    | { kind: 'number'; min?: number; max?: number }
    | { kind: 'select'; options: FieldOption[] }
    | { kind: 'radio'; options: FieldOption[] }
    | { kind: 'slot' }
    | { kind: 'color' }
    | { kind: 'background' }
    | { kind: 'image' }
    | { kind: 'url' }
    | { kind: 'action' }
    | { kind: 'dataMap'; itemFields?: ManifestField[] }
    | { kind: 'array'; itemFields: ManifestField[]; itemLabel?: string };

/**
 * Who a prop is tuned by, which decides the panel tier it appears in.
 *
 * Presentation only: a `design` field is still a normal prop, still stored, still rendered —
 * it is merely not offered as a control to ops.
 */
export type FieldAudience = 'ops' | 'design';

export interface ManifestField {
    name: string;
    label: string;
    /** Engineer-facing JSDoc body extracted from the prop type. */
    description?: string;
    field: FieldDescriptor;
    defaultValue?: unknown;
    required: boolean;
    /**
     * Overrides the editor's default tier for this prop. Unset means the editor derives it from
     * `field.kind`, so nothing needs per-field authoring to get a sane tier.
     */
    audience?: FieldAudience;
    /** Ops-facing help, in plain language. Distinct from {@link ManifestField.description}. */
    help?: string;
    /**
     * Ops-facing answer labels for a `select`/`radio`, as `value → label`. Keys are the option
     * value stringified. The VALUE is never changed — only the gloss around it.
     */
    answers?: Record<string, string>;
}

export type ComponentSource = 'engine' | 'dp-design';

export interface ComponentManifest {
    name: string;
    source: ComponentSource;
    category?: string;
    fields: ManifestField[];
    slotFields: string[];
}

export interface Manifest {
    version: number;
    components: ComponentManifest[];
}

const data = manifestData as unknown as Manifest;

/** The full manifest payload (`{ version, components }`). */
export const manifest: Manifest = data;

/** Every component manifest, as an array. */
export const components: ComponentManifest[] = data.components;

/** Component manifests keyed by component name — e.g. `manifests.WhatsNew`. */
export const manifests: Record<string, ComponentManifest> = Object.fromEntries(
    data.components.map((c) => [c.name, c]),
);

export default manifests;
