/**
 * pandora-box-manifest — builder component manifests (field descriptors) for the Pandora Box
 * low-code engine's layout components. Generated by the engine extractor (the SSOT) and shipped
 * as DATA, so a builder OR a project reads the exact field config the builder uses
 * ("builder == delivered"). Pairs 1:1 with `pandora-box-layout` (the runtime components).
 *
 * Zero runtime deps: the manifest is plain JSON + these structural types (a copy of the engine
 * protocol). Use the exported types directly, or assign to your own `ComponentManifest`
 * (e.g. from pandora-box-react) with a cast — the shapes match.
 */
import manifestData from './manifest.json';

export interface FieldOption {
    label: string;
    value: string | number | boolean;
}

export type FieldDescriptor =
    | { kind: 'text' }
    | { kind: 'textarea' }
    | { kind: 'number'; min?: number; max?: number }
    | { kind: 'select'; options: FieldOption[] }
    | { kind: 'radio'; options: FieldOption[] }
    | { kind: 'slot' }
    | { kind: 'color' }
    | { kind: 'background' }
    | { kind: 'image' }
    | { kind: 'url' }
    | { kind: 'action' }
    | { kind: 'dataMap'; itemFields?: ManifestField[] }
    | { kind: 'array'; itemFields: ManifestField[]; itemLabel?: string };

export interface ManifestField {
    name: string;
    label: string;
    description?: string;
    field: FieldDescriptor;
    defaultValue?: unknown;
    required: boolean;
}

export type ComponentSource = 'engine' | 'dp-design';

export interface ComponentManifest {
    name: string;
    source: ComponentSource;
    category?: string;
    fields: ManifestField[];
    slotFields: string[];
}

export interface Manifest {
    version: number;
    components: ComponentManifest[];
}

const data = manifestData as unknown as Manifest;

/** The full manifest payload (`{ version, components }`). */
export const manifest: Manifest = data;

/** Every component manifest, as an array. */
export const components: ComponentManifest[] = data.components;

/** Component manifests keyed by component name — e.g. `manifests.WhatsNew`. */
export const manifests: Record<string, ComponentManifest> = Object.fromEntries(
    data.components.map((c) => [c.name, c]),
);

export default manifests;
